site_name: Grupo BRIET 
site_url: https://grupobriet.com/
site_author: Gabriel Macedo
site_description: >-
  Site do Grupo de Pesquisa BRIET - #grupobriet - 
  Instituto Brasileiro de Informação em Ciência e 
  Tecnologia - IBICT - Universidade Federal do 
  Rio de Janeiro - UFRJ

# Repository
repo_name: grupo-briet.github.io
repo_url: https://github.com/grupo-briet/grupo-briet.github.io
edit_uri: edit/main/docs/

## Tema
theme:
  name: material
  custom_dir: overrides
  include_search_page: false
  search_index_only: true
  highlightjs: true
  hljs_languages:
    - yaml
  sticky_navigation: true
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: deep purple
      accent: orange        
      toggle:
        icon: material/weather-night
        name: Trocar para modo escuro
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: light blue      
      toggle:
        icon: material/weather-sunny
        name: Trocar para modo claro
  language: pt-BR
  icon:
#    logo: material/book-open-page-variant
#    logo: material/alpha-b-box
    logo: material/graph
    edit: material/pencil 
    view: material/eye
  favicon: briet.png
  font:
    text: 'Roboto'
    code: 'Roboto Mono'
  features:
    - content.action.edit
    - navigation.footer
    - navigation.tabs
    - navigation.instant    
#    - navigation.expand
#    - navigation.top
#    - navigation.sections
    - navigation.tracking
    - search.suggest
    - search.highlight
    - search.share
    - toc.integrate 
# 404 page
  static_templates:
    - 404.html

markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - meta
  - md_in_html
  - toc:
      slugify: !!python/object/apply:pymdownx.slugs.slugify {kwds: {case: lower}}
      permalink: '#'
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:materialx.emoji.to_svg
      emoji_index: !!python/name:materialx.emoji.twemoji
      options:
        custom_icons:
          - overrides/.icons      
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.keys      
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
        - name: vegalite
          class: vegalite
          format: !!python/name:mkdocs_charts_plugin.fences.fence_vegalite  
  - pymdownx.tabbed:
      alternate_style: true  
      slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower      
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.magiclink
  - pymdownx.tilde
  - pymdownx.progressbar
  - tables
     
# Plugins
plugins:
  - search:
      lang: pt  
      separator: '[\s\-,:!=\[\]()"`/]+|\.(?!\d)|&[lg]t;|(?!\b)(?=[A-Z][a-z])'
# Padrão do separador de busca: separator: '[\s\-\.]+' substituído por "\s"
#      separator: '[\s]+'
# 3 já é o padrão      min_search_length: 3
#  - git-revision-date
  - charts
  - table-reader
  - macros
  - mermaid2:
      arguments:
        securityLevel: 'loose'      
        theme: |
            ^(window.matchMedia && window.matchMedia('(prefers-color-scheme: dark)').matches) ? 'dark' : 'light'
#  - tags:
#      tags_file: tags.md
  - social
  - minify:
      minify_html: true

extra:
#  disqus: briet
  analytics:
    provider: google
    property: G-6YL8EL6LW5
#    feedback:
#      title: Esta página foi útil?
#      ratings:
#        - icon: material/emoticon-happy-outline
#          name: Essa página está boa!
#          data: 1
#          note: >-
#            Obrigado pelo seu feedback!
#        - icon: material/emoticon-sad-outline
#          name: Essa página deve ser melhorada!
#          data: 0
#          note: >- 
#            Obrigado pelo seu feedback! Nos ajude a melhorar essa página
#            preenchendo nosso <a href="..." target="_blank" rel="noopener">formulário de feedback</a>.
  consent:
    title: Consentimento para uso de cookies
    description: >- 
      Usamos cookies para reconhecer sua visita e identificar suas
      preferências, além de medir a eficácia do conteúdo e da ferramenta 
      de busca. Seu consentimento nos ajuda a compreender melhor o uso do 
      site.
  social:
    - icon: fontawesome/regular/envelope
      link: mailto:luanasales@ibict.br
      name: Email - BRIET
    - icon: fontawesome/brands/youtube
      link: https://www.youtube.com/channel/UCwbvIl-TSZOSritOESaukQQ
      name: Youtube - BRIET
#    - icon: fontawesome/brands/instagram
#      link: https://www.instagram.com/grupobriet
#      name: Instagram - BRIET
    - icon: fontawesome/brands/github
      link: https://grupo-briet.github.io/
      name: Github - BRIET
#    - icon: fontawesome/brands/facebook
#      link: https://www.facebook.com/people/GRUPO-de-pesquisa-BRIET/100076347663252/
#      name: Facebook

# Copyright
copyright: >-
    Apoio: ![CNPq](https://www.gov.br/cnpq/pt-br/canais_atendimento/identidade-visual/CNPq_v2017_rgb_neg.png){ width=50 } </br>
    Copyright &copy; 2023 Grupo BRIET 
    - <a href="#__consent">Alterar as preferências de cookies.</a>
      
# CSS
extra_css:
  - stylesheets/extra.css

extra_javascript:
  - https://unpkg.com/mermaid/dist/mermaid.min.js
  - https://cdn.jsdelivr.net/npm/vega@5
  - https://cdn.jsdelivr.net/npm/vega-lite@5
  - https://cdn.jsdelivr.net/npm/vega-embed@6
  - https://unpkg.com/tablesort@5.3.0/dist/tablesort.min.js
  - javascripts/tablesort.js
